### PR TITLE
fix `du` showing 0 by making getattr set st_blksize/st_blocks

### PR DESCRIPTION
**Pull request by rmmh**
du by default sums disk usage (the number of blocks used by a file) instead of file size directly. Tar files are a series of 512B blocks, so we report a 1-block header + ceil(filesize / 512).

### CODE REVIEW

**Comment by rmmh** [comment]
As an aside, st_nlink should probably be set to 1 instead of 2, or even better, the number of hardlinks present in the tarfile.

**Comment by mxmlnkn** [comment]
Hi, thank you for your contribution!

I think, I'll merge this for now except if you say you wanna improve upon it a bit more?

It makes things better than the current state but it isn't a perfect fix yet.
Issues to be addressed:

 - Would it be better to use the actual TAR block size? What about TARs with other block sizes than 512B?
 - What about union mounts of systems with different block sizes? I guess, all blocks, if they can be queried, could be converted to the least common factor of 512B per block.
 - Does it work for sparse files?
 - How do I treat folders?
 - Do I have to advertise the blocksize somewhere so that it can be queried? [Seems like](https://serverfault.com/questions/29887/how-do-i-determine-the-block-size-of-an-ext3-partition-on-linux) it can, e.g., be queried with `stat -fc %s .`.
 - Tests would be nice.
 - Personally, I'd prefer an actual readable `ceil( size / 512 )` instead of the bitshifts. I don't think it makes any difference in performance as pure Python isn't the fastest to begin with.

After merging this, I would see what I can do about these issues myself.

As for `st_nlink`, I don't see or remember why I set it to 2. Seems dumb. Maybe I checked what stat returns for a test file and just used that as a dummy value and that test file might have been hardlinked to by chance. Never needed `st_nlink`.

**Comment by rmmh** [comment]
> Would it be better to use the actual TAR block size? What about TARs with other block sizes than 512B?
Most tar files are 512B-- I know there are some nonstandard ones with different block sizes, but they seem rare. I think it's fine for this disk usage to be approximate, since most tarballs are compressed and the actual space a file takes will be difficult to determine.

> What about union mounts of systems with different block sizes? I guess, all blocks, if they can be queried, could be converted to the least common factor of 512B per block.
It will be even more approximate, but the sizes should be vaguely correct. You could pass through the underlying file's block sizes if available.

> Does it work for sparse files?
No, I'm not sure how to find the actual space of sparse files in an archive. I guess you'd need to compute the gap in offsets between the file and the next one in the archive? That's actually not too hard to do using rowids (or total file length for the last file), but it feels weird.

> How do I treat folders?
Folders are 0-byte files marked as folders in the tarfile, so they are reported as taking one 512B header block.

> Do I have to advertise the blocksize somewhere so that it can be queried? Seems like it can, e.g., be queried with stat -fc %s ..
blocksize can be different for each file. 512 is just a decent default.

> Tests would be nice.
I had a look at the bash tests and didn't have the time to figure out how to add one. It shouldn't be too hard to write a stat test, though! :-)

> Personally, I'd prefer an actual readable ceil( size / 512 ) instead of the bitshifts. I don't think it makes any difference in performance as pure Python isn't the fastest to begin with.
Removed bitshifts.

I added a couple more commits for other nits, feel free to merge if this is a good enough starting point before you address the other issues.

**Comment by mxmlnkn** [comment]
> > Would it be better to use the actual TAR block size? What about TARs with other block sizes than 512B?
> 
> Most tar files are 512B-- I know there are some nonstandard ones with different block sizes, but they seem rare. I think it's fine for this disk usage to be approximate, since most tarballs are compressed and the actual space a file takes will be difficult to determine.

Compressed TARs and block sizes are indeed an issue I shortly thought about. It wouldn't be impossible to return a real block size but then the number of blocks would show the compressed filesize and therefore files might be erroneously detected as sparse. So I'd decide against using the actual compressed blocks anyways. Compression should be treated like it is hidden.

> > Does it work for sparse files?
> 
> No, I'm not sure how to find the actual space of sparse files in an archive. I guess you'd need to compute the gap in offsets between the file and the next one in the archive? That's actually not too hard to do using rowids (or total file length for the last file), but it feels weird.

I looked again and tarfile just does not seem to give me this information. It's vexing. However, it could be easily deduced from the ordered offsets of all files, so maybe that's why. So if you have a file name you want the real size on disk of, you could do this SQLite query on the ratarmount index:

```sql
SELECT offset FROM files WHERE offset >= (
    SELECT offset FROM files WHERE path == '/foo' AND name == 'bar.jpg' 
) ORDER BY offset LIMIT 2;
```

Then just take the difference between the two returned offsets for the real file size. However, this might require an extra SQL index on the offset column to speed up this kind of lookup to logarithmic complexity.

> > Tests would be nice.
> 
> I had a look at the bash tests and didn't have the time to figure out how to add one. It shouldn't be too hard to write a stat test, though! :-)

Sorry about that. They are basically freeform tests for now. Anything goes as long as they exit with code 0 on success and anything else on failure. Might try to port them to some Python test framework in the future. I just don't know which one to use, yet.

> I added a couple more commits for other nits, feel free to merge if this is a good enough starting point before you address the other issues.

Will do. Thanks.

**Comment by rmmh** [comment]
>    SELECT offset FROM files WHERE offset >= (SELECT offset FROM files WHERE path == '/foo' AND name == 'bar.jpg'  ) ORDER BY offset LIMIT 2;

You can do a little better than that, given how SQLite allocates rowids incrementally:
`SELECT offset FROM files WHERE rowid = (select rowid+1 FROM files WHERE path == '/foo' AND name == 'bar.jpg')`

**Pull request merged**
