### PR TITLE
Transform password cli argument to bytes type

### PR DESCRIPTION
**Pull request by Vadiml1024**
The current version have a problem with opening password protected .zip files if the password was specified
using **--password** cli argument because ZipFile **open** and **setpassword** methods expect the password to have **bytes** type and  not **str**.

### CODE REVIEW

**Comment by mxmlnkn** [comment]
Thank you for reporting this bug and also showing the fix!

Could you elaborate on the --eager option? Why do you need that? It doesn't seem to belong to this pull request.

**Comment by Vadiml1024** [comment]
the need for --eager option arises in following situation:
Suppose you have a directory* testdir* with files *ar1.zip* and *ar2.zip*
and you do:

ratarmount -r -l testdir /mnt
ls -l /mnt

this will list ar1.zip and ar2.zip as
*files*
with --eager option they are  listed as *directories*


You're right about the fact that --eager option commit does not belong to
this merge request -
it is first time I'm using github.dev and somehow this commit landed in the
wrong branch *after* a published the merge request...

**Comment by mxmlnkn** [comment]
> the need for --eager option arises in following situation:

I see. I think the problem should be solvable more generically and maybe even without the need of adding another option. I think, I had a version, which did mount files when `readdir` was called.

The problem with that was that there seem to be a lot of system software that monitors new mount points and then calls readdir on them when they are mounted. This leads to archives in the top-level always being mounted even when specifying `--lazy`. That might be unexpected to the user.

Another possibility would be to return the mounted folders on readdir without doing the actual work of mounting. However, this runs into problems when we can't determine whether an archive is valid before mounting, e.g., because the archive is invalid. At that point we would already have returned a recursive mount folder, which would disappear when trying to access it because only then would it determine that it cannot be mounted.

Thinking about it, the second option doesn't seem all that bad to me. That's just how lazy is.

> You're right about the fact that --eager option commit does not belong to
> this merge request -
> it is first time I'm using github.dev and somehow this commit landed in the
> wrong branch *after* a published the merge request...

A merge request is not "published" per se, it is opened on a branch, which also means that any changes you push to that branch will also modify the merge request. That's why you normally create a feature branch other than "master" and then you open the merge request on that feature branch.

Would you be fine if I simply applied the `.encode` fix myself instead? I would then close the merge request without merging it.

**Comment by Vadiml1024** [comment]
First of all sure, please feel free to use any part of patch as you wish.

Btw, it seems that I've misinterpreted my experiments with ratarmount so
the example i proposed actually
works very well without  the --eager option.

**Comment by mxmlnkn** [comment]
I implemented the fix and some additional tests and additional CI fixes. I also moved the AppImage step into a separate workflow, which can be manually triggered.

**Pull request closed without merging**
