### PR TITLE
Fix (path, name) query to work with older versions of sqlite (on ubuntu 16)

### PR DESCRIPTION
**Pull request by epicfaace**
Based on @mxmlnkn 's approach in https://github.com/codalab/codalab-worksheets/pull/3893#issuecomment-984073323.

### CODE REVIEW

**Comment by mxmlnkn** [comment]
Because it indeed has performance implications, I fixed it in a bit more roundabout manner by testing for the libsqlite version. The commit 1a94f94e9cf2d540b364b904188d1800d06ef88e is already on master. I would appreciate your feedback on whether the current master fixes your problems so that I can release ratarmountcore 0.1.2.

**Comment by epicfaace** [comment]
Got it, yes, I think that should work! Thanks for adding that fix.

**Comment by mxmlnkn** [comment]
0.1.2 is released.

**Comment by epicfaace** [comment]
Thanks!!

--
Ashwin Ramaswami

**Pull request closed without merging**
